version: "3"

services:
  reddit-bot:
    image: reddit-bot:${IMAGE_TAG}
    container_name: reddit-bot
    restart: unless-stopped
    volumes:
      - "./data/logs:/reddit-bot/logs"
    environment:
      - REDDITBOT_DISCORD_TOKEN=${DISCORD_TOKEN}
